# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.2‘

# The target name is most likely the name of your project.
target ‘camera_app‘ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for camera_app
  #
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod ‘React‘, :path => ‘../node_modules/react-native‘, :subspecs => [
    ‘Core‘,
    ‘BatchedBridge‘,
    ‘RCTText‘,
    ‘RCTNetwork‘,
    ‘RCTAnimation‘,
    ‘RCTImage‘,
    ‘RCTWebSocket‘, # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod ‘Yoga‘, :path => ‘../node_modules/react-native/ReactCommon/yoga‘
  pod ‘BVLinearGradient‘, :path => ‘../node_modules/react-native-linear-gradient‘
  pod ‘PxPlayer‘, :path => ‘./camera_app/react-native-pxplayer‘
  pod ‘GVRSDK/GVRView‘
end
